dist: xenial      # to use stable Python 3.7

language: python

cache: pip  # cache pip packages, we're not shipping code,
            # only care about dependencies being installed

python:
  - "3.7"

script:
  - black --check ci
  - mypy ci
  - pytest -v
