version: 2.1

jobs:
  test:
    docker:
      - image: python:3.8-slim
    steps:
      - checkout
      - pip install -r requirements.txt
      - run:
          command: black --check ci/
          name: Black check
      - run:
          command: mypy ci/
          name: Mypy check
      - run:
          command: flake8 ci/
          name: Flake8 check
      - run:
          command: isort --check-only -rc ci/
          name: isort check
      - run:
          command: pytest -v ci/
          name: Test
