name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 20 * * *" # every day at 20:00 UTC

env:
  USER_AGENT: Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0

jobs:
  test-links-valid:
    runs-on: ubuntu-latest
    container:
      image: lycheeverse/lychee:latest
      env:
        GITHUB_TOKEN: $LYCHEE_GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check external links using lychee
        run: |
          # some websites reject requests from GitHub
          lychee --verbose -X head --user-agent="$USER_AGENT" --timeout 45 --max-concurrency 16 --exclude dropbox.tech --exclude kerkour.com --exclude toptal.com --exclude reddit.com --exclude usenix.org README.md
          # dropbox.tech doesn't like HEAD requests
          lychee --verbose -X get  --user-agent="$USER_AGENT" --timeout 45 --max-concurrency 1  --include dropbox.tech README.md

  test-links-sorted:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v1
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync
          uv tool install rust-just

      - name: Check ruff format
        run: |
          just check_format

      - name: Check mypy
        run: |
          just check_mypy

      - name: Check ruff
        run: |
          just check_ruff

      - name: Test if links are sorted in README.md
        run: |
          just test
