name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 20 * * *'    # every day at 20:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      env:
        cache-name: cache-venv-pip-poetry
      with:
        path: ~/.cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        make ci_setup
        make install

    - name: Black (code formatting) check
      run: |
        make check_black

    - name: Mypy (typecheck) check
      run: |
        make check_mypy

    - name: Flake8 (lint) check
      run: |
        make lint

    - name: isort (imports) check
      run: |
        make check_isort

    - name: Test
      run: |
        make test
