name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 20 * * *'    # every day at 20:00 UTC

jobs:
  test-links-valid:
    runs-on: ubuntu-latest
    needs: checkout
    container:
      image: lycheeverse/lychee:latest
      options: --user 0
      env:
        GITHUB_TOKEN: $LYCHEE_GITHUB_TOKEN

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check external links using lychee
      run: |
        /usr/src/lychee/lychee --progress --verbose README.md

  test-links-sorted:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      id: cache
      env:
        cache-name: cache-pip-poetry
      with:
        path: ~/.cache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"

    - name: CI setup
      run: |
        make ci_setup

    - name: Install dependencies
      run: |
        make install
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Black (code formatting) check
      run: |
        make check_black

    - name: Mypy (typecheck) check
      run: |
        make check_mypy

    - name: Flake8 (lint) check
      run: |
        make lint

    - name: isort (imports) check
      run: |
        make check_isort

    - name: Test if links are sorted in README.md
      run: |
        make test_not_external
